<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BannerRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'id'=>'required|numeric|exists:id'
        ];
    }
    public  function  messages()
    {
        return [
            'id.required'=>'Tồn Tại',
            'id.numeric'=>'Đúng Định Dạng',
            'id.exists'=>'Không Tồn Tại Dữ Liệu Trên',
        ]; // TODO: Change the autogenerated stub
    }
}
