export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL"
export const FETCH_CATEGORY_PRODUCT = "FETCH_CATEGORY_PRODUCT"
export const MADANHMUC = "MADANHMUC"
export const PRODUCTMADANHMUC = "PRODUCTMADANHMUC"
export const KEYWORD = "KEYWORD"
export const SEARCH = "SEARCH"
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART"
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART"
export const DANGKY = "DANGKY"
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'
export const IMPORT_CART_FROM_STORAGE = 'IMPORT_CART_FROM_STORAGE'
export const nameOfLocalStore = {
    TaiKhoan: "TaiKhoan"
};
export const FETCH_SLIDER = "FETCH_SLIDER"